version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: avito-shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    networks:
      - internal

networks:
  internal: